### ISSUE TITLE
Syntax Error on starting soul

### ISSUE THREAD

**Issue by mbernaschi** [thevahidal/soul#141]
Hello to everyone, I installed (apparently successfully) soul on a Debian system (the following is the output of the uname -a command)
Linux gg-rwd-ey-prod 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
but when I start soul (/usr/local/bin/soul) I got the following error
/usr/local/lib/node_modules/soul-cli/src/config/index.js:80
    origin: argv.cors?.split(',') ||
                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/soul-cli/src/index.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

I don't know if it is relevant, but the output of /usr/bin/js -v is
v12.22.12

Is there any pre-requisite that I should install before running soul?
Thanks in advance for any help,
Massimo

**Comment by mbernaschi** [comment]
I upgraded node to v18.18.2 and now soul starts!

**Comment by mbernaschi** [comment]
Sorry for the message bombing. It works fine (reading also the tables of the DB) running as root but if I run it as an ordinary user
I get a Segmentation fault although I use a non privileged port (8000). Any clue?
Thanks in advance!
