### ISSUE TITLE
Thanks. After upgrade it fails with:

### ISSUE THREAD

**Issue by maacl** [thevahidal/soul#50]
Thanks. After upgrade it fails with:

```
PS C:\Users\marti\tmp\soul-test> soul -port 8080 -d sakila.db
C:\Users\marti\AppData\Roaming\npm\node_modules\soul-cli\src\config\index.js:43
  throw new Error(`Config validation error: ${error.message}`);
  ^

Error: Config validation error: "NODE_ENV" is required
```

_Originally posted by @maacl in https://github.com/thevahidal/soul/issues/48#issuecomment-1296260940_

**Comment by thevahidal** [comment]
@maacl, this issues should be fixed in v0.0.5

**Comment by maacl** [comment]
With 0.0.5 on Linux this now fails with:

```
❯ soul -d sakila-master.db -p 8000
/mnt/c/Users/marti/AppData/Roaming/npm/node_modules/soul-cli/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /mnt/c/Users/marti/AppData/Roaming/npm/node_modules/soul-cli/node_modules/better-sqlite3/build/Release/better_sqlite3.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/mnt/c/Users/marti/AppData/Roaming/npm/node_modules/soul-cli/node_modules/bindings/bindings.js:112:48)
    at new Database (/mnt/c/Users/marti/AppData/Roaming/npm/node_modules/soul-cli/node_modules/better-sqlite3/lib/database.js:48:64)
    at new Database (/mnt/c/Users/marti/AppData/Roaming/npm/node_modules/soul-cli/src/db/index.js:7:15)
    at Object.<anonymous> (/mnt/c/Users/marti/AppData/Roaming/npm/node_modules/soul-cli/src/db/index.js:26:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by thevahidal** [comment]
@maacl,
This might be related to these issues from Better-Sqlite3
- https://github.com/WiseLibs/better-sqlite3/issues/493
- https://github.com/WiseLibs/better-sqlite3/issues/542

I think maybe the node_modules is messed up due to updating it multiple times. I would suggest that it might help to completely delete `soul` and its `node_modules` (It should be inside `/usr/lib/`, try `npm list -g`) and then re-install it again.

**Comment by maacl** [comment]
Nope, tried that. Still getting the same error.

**Comment by thevahidal** [comment]
@maacl,
I just created a replit project to see if there are any problems and it didn't have any.
here's the link to replit for you to test:
- https://replit.com/join/cwdaxztggr-thevahidal

**Comment by maacl** [comment]
Ah, I figured it out. I am using WSL and I have soul installed on the host
too, which is what it was trying to run under WSL. Using the full path to
the WSL binary worked.

**Comment by thevahidal** [comment]
Great, Glad that it's finally working.
